project:
  type: website
  output-dir: docs

website:
  title: "Ashlee Patacsil-Hardin"
  navbar:
    left:
      - href: index.qmd
        text: About
      - about.qmd
      - projects.qmd
      - facts.qmd
      

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

